### ISSUE TITLE
sendRequest response arrives without token

### ISSUE THREAD

**Issue by alexfromsofia** [allynsweet/E2E-Mailbox#4]
<img width="731" alt="Screenshot 2024-06-14 at 10 09 20" src="https://github.com/allynsweet/E2E-Mailbox/assets/26092159/d098da91-5b89-4f60-8465-ea53fc961403">

PS: I'm running on latest version `1.1.4`

**Comment by allynsweet** [comment]
I just ran the tests and inspected this situation, it appears your error is saying `result` is null. I cannot replicate this, which suggests it could have been due to a networking issue.

In any case, in this situation the opposite mailbox provider should be used instead of outright failing. I'm pushing a patch now (1.1.15) that should fix this if it happens again.

Thank you for reporting!
